package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hashset",
    srcs = [
        "hashset.cc",
    ],
    hdrs = [
        "hashset.h",
    ],
    defines = ["BAZEL_BUILD"],
    deps = [
        "//api",
        "//sdk:headers",
    ],
)
