cc_binary(
    name = "miv_otlp",
    srcs = [
        "main.cc",
    ],
    linkopts = ["-pthread"],
    tags = [
        "examples",
        "otlp",
        "miv_otlp",
    ],
    deps = [
        "//api",
        "//examples/hashset:hashset",
        "//exporters/otlp:otlp_http_exporter",
        "//exporters/otlp:otlp_http_exporter",
        "//sdk/src/trace",
    ],
)
)
